tasks:
  - name: install
    init: npm install && gp sync-done install
  - name: kitae
    init: gp sync-await install && gp env > ./apps/kitae/.env
    command: npm run kitae:dev

vscode:
  extensions:
    - astro-build.astro-vscode
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - csstools.postcss
